use_frameworks!

platform :ios, '9.0'

target 'TSGradientCycleAnimationView_Example' do
  pod 'TSGradientCycleAnimationView', :path => '../'

  target 'TSGradientCycleAnimationView_Tests' do
    inherit! :search_paths

    
  end
end
